[package]
name = "palindrome_partitioning"
version = "0.1.0"
edition = "2021"
authors = ["upendra upadhyay"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
